import type { NextPage } from "next";
import Head from "next/head";
import styled from "styled-components";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <div>
          <Link href="/beers">
            <a>
              <Img
                src="https://cdn.pixabay.com/photo/2017/06/24/23/41/beer-2439237_1280.jpg"
                alt="맥주"
              />
            </a>
          </Link>
        </div>
        <div>
          <Link href="/wines">
            <a>
              <Img
                src="https://cdn.pixabay.com/photo/2021/11/17/06/33/wine-6802684_1280.jpg"
                alt="와인"
              />
            </a>
          </Link>
        </div>
      </Main>

      <footer></footer>
    </div>
  );
};

export default Home;

const Main = styled.main`
  display: flex;
  width: 100%;
  justify-content: space-between;
  padding: 50px;
`;

const Img = styled.img`
  width: 35em;
  height: 30em;
  border-radius: 5em;
`;
